on:
  workflow_dispatch:

jobs:
  j1:
    name: Generate Access Report of GitHub
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
#          repository: bob/nice-project
          repository: ${{ github.repository }}
