# licensed というツールを使って submodule のライセンスをチェックします。

name: Check Submodule License

on:
  push:
  workflow_dispatch:

jobs:
  check-submodule-license:
    runs-on: ubuntu-20.04

  steps:

    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
        with:
          version: '4.x'

    - run: licensed cache
    - run: licensed status
