
# github actions でビルドしてDLL等の成果物をアップロードする手順です。

name: Upload DLLs

# 手動でgithubサイトのボタンを押したときか、タグを作ったときに実行します。
on:
  workflow_dispatch:
  create:
    tags: '*'

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  # 1つ目のジョブです。
  # OS別にビルドして、それぞれの成果物をアーティファクトとして保存します。
  upload-dlls:

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-18.04]

    steps:


      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.KEY_TO_ACCESS_FBXSDK }}

      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Build
        uses: ./.github/actions/build
        with:
          shell_type: ${{ (runner.os == 'Windows' && 'powershell') || 'bash' }}

      - name: Copy DLL for Windows
        if: runner.os == 'Windows'
        run: |
          mkdir D:\a\output -Force
          Copy-Item -Filter "*.dll" -Path ${{github.workspace}}\out\build\x64-Release\bin\* -Destination D:\a\output
          Copy-Item -Path ${{github.workspace}}\wrappers\csharp\LibPLATEAU.NET\CSharpPLATEAU\bin\Release\netstandard2.0\CSharpPLATEAU.dll -Destination D:\a\output

      - name: Copy lib for Windows
        if: runner.os == 'Windows'
        run: |
          Copy-Item -Path ${{ github.workspace }}\out\build\x64-Release\3rdparty\libcitygml\lib\citygml.lib -Destination D:\a\output
          Copy-Item -Path ${{ github.workspace }}\out\build\x64-Release\src\plateau.lib -Destination D:\a\output

      - name: Upload DLL for Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: libplateau-windows-dll
          path: D:\a\output

      - name: Copy Libraries for Ubuntu and MacOS
        if: runner.os != 'Windows'
        run: |
          mkdir $HOME/output/
          find ${{github.workspace}}/out/build/x64-Release -name *.so -or -name *.dylib -or -name libcitygml.a | xargs -I {} cp -v {} $HOME/output
          echo "HOME=$(echo $HOME)" >> $GITHUB_ENV

      - name: Upload DLL(so, dylib) for Ubuntu and MacOS
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: libplateau-${{matrix.os}}-dll
          path: ${{env.HOME}}/output/


  # 2つ目のジョブです。
  # OSごとのアーティファクトを1つにまとめます。
  sum-up-dlls:
    runs-on: ubuntu-latest
    needs: upload-dlls

    steps:
      - name: download-all-artifacts
        uses: actions/download-artifact@v2
        with:
          path: ~/a

      - name: sum-up-dynamic-libs
        run: |
          mkdir -p ~/a/plateau-plugins/dynamic-libs/Windows/x86_64
          mkdir -p ~/a/plateau-plugins/dynamic-libs/Linux/x86_64
          mkdir -p ~/a/plateau-plugins/dynamic-libs/MacOS/x86_64
          mkdir -p ~/a/plateau-plugins/dynamic-libs/ManagedDLL
          cp ~/a/libplateau-windows-dll/plateau.dll ~/a/plateau-plugins/dynamic-libs/Windows/x86_64
          cp ~/a/libplateau-windows-dll/CSharpPLATEAU.dll ~/a/plateau-plugins/dynamic-libs/ManagedDLL
          cp ~/a/libplateau-ubuntu-18.04-dll/*.so ~/a/plateau-plugins/dynamic-libs/Linux/x86_64
          cp ~/a/libplateau-macos-latest-dll/*.dylib ~/a/plateau-plugins/dynamic-libs/MacOS/x86_64

      - name: sum-up-static-libs
        run: |
          mkdir -p ~/a/plateau-plugins/static-libs/windows
          mkdir -p ~/a/plateau-plugins/static-libs/linux
          mkdir -p ~/a/plateau-plugins/static-libs/macos
          cp ~/a/libplateau-windows-dll/*.lib ~/a/plateau-plugins/static-libs/windows
          cp ~/a/libplateau-ubuntu-18.04-dll/*.a ~/a/plateau-plugins/static-libs/linux
          cp ~/a/libplateau-macos-latest-dll/*.a ~/a/plateau-plugins/static-libs/macos

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: all-libraries
          path: ~/a/plateau-plugins
          
